### ISSUE TITLE
`cargo test` fails

### ISSUE THREAD

**Issue by ignatenkobrain** [magiclen/path-absolutize#2]
```rust
running 13 tests
test src/lib.rs - Absolutize::absolutize (line 40) ... ok
test src/lib.rs - Absolutize::absolutize (line 27) ... ok
test src/lib.rs - Absolutize::absolutize (line 112) ... FAILED
test src/lib.rs - Absolutize::absolutize_virtually (line 173) ... ok
test src/lib.rs - Absolutize::absolutize (line 132) ... FAILED
test src/lib.rs - Absolutize::absolutize (line 78) ... FAILED
test src/lib.rs - Absolutize::absolutize (line 56) ... FAILED
test src/lib.rs - Absolutize::absolutize_virtually (line 187) ... ok
test src/lib.rs - Absolutize::absolutize_virtually (line 264) ... ok
test src/lib.rs - Absolutize::absolutize_virtually (line 224) ... ok
test src/lib.rs - Absolutize::absolutize_virtually (line 281) ... ok
test src/lib.rs - Absolutize::absolutize_virtually (line 203) ... ok
test src/lib.rs - Absolutize::absolutize_virtually (line 243) ... ok

failures:

---- src/lib.rs - Absolutize::absolutize (line 112) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


---- src/lib.rs - Absolutize::absolutize (line 132) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


---- src/lib.rs - Absolutize::absolutize (line 78) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


---- src/lib.rs - Absolutize::absolutize (line 56) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src/lib.rs - Absolutize::absolutize (line 112)
    src/lib.rs - Absolutize::absolutize (line 132)
    src/lib.rs - Absolutize::absolutize (line 56)
    src/lib.rs - Absolutize::absolutize (line 78)
```

Not sure what might be the problem, but I believe the same causes https://github.com/sharkdp/bat/issues/1022

**Comment by ignatenkobrain** [comment]
Oh, also

```rust
---- absolutize_after_updating_cwd stdout ----
thread 'absolutize_after_updating_cwd' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- absolutize_lv1_1 stdout ----
thread 'absolutize_lv1_1' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9

---- absolutize_lv1_2 stdout ----
thread 'absolutize_lv1_2' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9

---- absolutize_lv2 stdout ----
thread 'absolutize_lv2' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9

---- absolutize_lv3 stdout ----
thread 'absolutize_lv3' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/path-dedot-1.2.4/src/cwd.rs:58:9


failures:
    absolutize_after_updating_cwd
    absolutize_lv1_1
    absolutize_lv1_2
    absolutize_lv2
    absolutize_lv3
```

Though the `--test-threads=1` does not help.

**Comment by magiclen** [comment]
Thank you again. It's been fixed.

**Comment by ignatenkobrain** [comment]
Yup, fixes the issue. Thanks!
